version: '3'

services:
  db:
    image: 'postgres:14.1'
    container_name: 'ecommerce-postgres'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge
